services:
  db:
    image: postgres:17.4
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: ${ENV_POSTGRES_DB}
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - devdojo-db:/var/lib/postgresql/data/

volumes:
  devdojo-db: