spring:
  profiles:
    active: postgresql
  application:
    name: anime-service
  threads:
    virtual: # thread virtual que custa menos para o sistema operacional
      enabled: true

logging:
  level:
    org.yvesguilherme: debug
#    root: debug

server:
  servlet:
#    context-path: /${spring.application.name}/v1
    context-path: /v1
  error:
    include-stacktrace: on_param
  jetty: # tomcat
    threads:
      max: 20

database:
  url: mysqlDNS:3306
  username: yvesguilhermeMySQL
  password: gokuMySQL

application:
  title: Anime Service
  version: 1.0.0