spring:
#  profiles:
#    active: postgresql
  application:
    name: anime-service
  threads:
    virtual: # thread virtual que custa menos para o sistema operacional
      enabled: true

logging:
  level:
    org.yvesguilherme: debug
#    root: debug

server:
  servlet:
#    context-path: /${spring.application.name}/v1
    context-path: /v1
  error:
    include-stacktrace: on_param
  jetty: # tomcat
    threads:
      max: 20

database:
  url: ${DB_URL:mysqlDNSDefault}:${DB_PORT:3306}/${DB_DATABASE:anime_local}
  username: ${LOCAL_USERNAME:yvesguilhermeMySQLDefault}
  password: ${LOCAL_PASSWORD:gokuMySQLDefault}

application:
  title: Anime Service
  version: 1.0.0