spring:
  #  profiles:
  #    active: postgresql
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: anime-service
  threads:
    virtual: # thread virtual que custa menos para o sistema operacional
      enabled: true
  datasource:
    url: jdbc:postgresql://${ENV_POSTGRES_HOST}:${ENV_POSTGRES_PORT}/${ENV_POSTGRES_DATABASE}?useSSL=false&applicationName=AnimeService&options=-c%20timezone=UTC
    username: ${ENV_POSTGRES_USER:root}
    password: ${ENV_POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool-1
      connection-test-query: SELECT 1
      validation-timeout: 3000
      leak-detection-threshold: 15000
      auto-commit: false
  jpa:
    show-sql: true

logging:
  level:
    org:
      yvesguilherme: debug
      hibernate: warn
#    root: debug

server:
  servlet:
    #    context-path: /${spring.application.name}/v1
    context-path: /v1
  error:
    include-stacktrace: on_param
  jetty: # tomcat
    threads:
      max: 20

database:
  url: ${DB_URL:mysqlDNSDefault}:${DB_PORT:3306}/${DB_DATABASE:anime_local}
  username: ${LOCAL_USERNAME:yvesguilhermeMySQLDefault}
  password: ${LOCAL_PASSWORD:gokuMySQLDefault}

application:
  title: Anime Service
  version: 1.0.0